Return-Path: <linux-kernel-owner@vger.kernel.org>
X-Original-To: lists+linux-kernel@lfdr.de
Delivered-To: lists+linux-kernel@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 2AA871983F0
	for <lists+linux-kernel@lfdr.de>; Mon, 30 Mar 2020 21:11:08 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1727437AbgC3TLF (ORCPT <rfc822;lists+linux-kernel@lfdr.de>);
        Mon, 30 Mar 2020 15:11:05 -0400
Received: from mx2.suse.de ([195.135.220.15]:55922 "EHLO mx2.suse.de"
        rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
        id S1726672AbgC3TLF (ORCPT <rfc822;linux-kernel@vger.kernel.org>);
        Mon, 30 Mar 2020 15:11:05 -0400
X-Virus-Scanned: by amavisd-new at test-mx.suse.de
Received: from relay2.suse.de (unknown [195.135.220.254])
        by mx2.suse.de (Postfix) with ESMTP id 1026EAC58;
        Mon, 30 Mar 2020 19:11:04 +0000 (UTC)
Date:   Mon, 30 Mar 2020 21:11:03 +0200
Message-ID: <s5htv258xq0.wl-tiwai@suse.de>
From:   Takashi Iwai <tiwai@suse.de>
To:     "Dmitry V. Levin" <ldv@altlinux.org>
Cc:     alsa-devel@alsa-project.org, linux-kernel@vger.kernel.org
Subject: Re: [alsa-devel] [PATCH 5/5] ALSA: uapi: Drop asound.h inclusion from asoc.h
In-Reply-To: <20200330165311.GA11372@altlinux.org>
References: <20191220153415.2740-1-tiwai@suse.de>
        <20191220153415.2740-6-tiwai@suse.de>
        <20200330165311.GA11372@altlinux.org>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
Content-Type: text/plain; charset=US-ASCII
Sender: linux-kernel-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-kernel.vger.kernel.org>
X-Mailing-List: linux-kernel@vger.kernel.org

On Mon, 30 Mar 2020 18:53:11 +0200,
Dmitry V. Levin wrote:
> 
> Hi,
> 
> On Fri, Dec 20, 2019 at 04:34:15PM +0100, Takashi Iwai wrote:
> > The asound.h isn't always available while asoc.h itself is distributed
> > in alsa-lib package.  So we need to avoid the unnecessary inclusion of
> > asound.h from there.
> > 
> > Signed-off-by: Takashi Iwai <tiwai@suse.de>
> > ---
> >  include/uapi/sound/asoc.h | 1 -
> >  1 file changed, 1 deletion(-)
> > 
> > diff --git a/include/uapi/sound/asoc.h b/include/uapi/sound/asoc.h
> > index a74ca232f1fc..6048553c119d 100644
> > --- a/include/uapi/sound/asoc.h
> > +++ b/include/uapi/sound/asoc.h
> > @@ -17,7 +17,6 @@
> >  #define __LINUX_UAPI_SND_ASOC_H
> >  
> >  #include <linux/types.h>
> > -#include <sound/asound.h>
> >  
> >  /*
> >   * Maximum number of channels topology kcontrol can represent.
> 
> This has reached v5.6 and caused the following regression:
> 
> sound/asoc.h:214:14: error: 'SNDRV_CTL_ELEM_ID_NAME_MAXLEN' undeclared here (not in a function)
>   214 |  char string[SNDRV_CTL_ELEM_ID_NAME_MAXLEN];

What program caused it?  The change was done because it broke (already
years log) the old alsa-lib code.  So reverting it will break it
again.

OTOH, alsa-lib breakage could be worked around inside alsa-lib, so
likely I'm going to revert it.  But I'd like to know exact cases.


thanks,

Takashi

> 
> Please revert or fix in some way to make the uapi header compileable again.
> 
> Thanks,
> 
> 
> -- 
> ldv
> 
